## Docker compose file for postgres
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: etp
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
